name = "VanVleckRecursion"
uuid = "b035d78d-16e8-4eee-b57b-0bcdd92a70b5"
authors = ["Orjan Ameye <orjan.ameye@hotmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[compat]
Aqua = "0.8.11"
CheckConcreteStructs = "0.1"
Documenter = "1.11"
DocStringExtensions = "0.9.4"
ExplicitImports = "1.11"
JET = "0.9.18, 0.10"
LaTeXStrings = "1.4"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CheckConcreteStructs = "73c92db5-9da6-4938-911a-6443a7e94a58"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "CheckConcreteStructs", "ExplicitImports", "Test", "Aqua", "Documenter"]
